# Generated by Django 5.1.6 on 2025-02-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='coverArt',
            field=models.URLField(blank=True),
        ),
    ]
