# Generated by Django 5.1.6 on 2025-02-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_coverart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='coverArt',
        ),
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
