# Generated by Django 5.1.6 on 2025-02-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_coverart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='trackID',
            field=models.CharField(max_length=100),
        ),
    ]
