# Generated by Django 5.1.6 on 2025-03-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlistID',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
