# Generated by Django 5.1.6 on 2025-02-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_playlist_playlistid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='createdAt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='updateAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
