# Generated by Django 5.1.6 on 2025-03-01 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0004_alter_playlist_createdat_alter_playlist_updateat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='updateAt',
        ),
    ]
