# Generated by Django 5.1.6 on 2025-03-01 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0005_remove_playlist_createdat_remove_playlist_updateat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['name']},
        ),
    ]
